# Generated by Django 4.2 on 2025-12-10 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_usercourseenrollment_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['id'], 'verbose_name_plural': '4. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1. Teachers'},
        ),
        migrations.AlterModelOptions(
            name='usercourseenrollment',
            options={'ordering': ['-enrolled_date'], 'verbose_name_plural': '6. User Course Enrollments'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chapter_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.coursecategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='course_img/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='techs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interested_categories',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
