# Generated by Django 4.2 on 2025-12-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_quiz_quizsubmission_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempt_limit',
            field=models.IntegerField(default=1, help_text='Number of attempts allowed (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Due date for the quiz', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_quiz',
            field=models.BooleanField(default=True, help_text='Flag to identify as quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_answers',
            field=models.BooleanField(default=False, help_text='Show answers after submission'),
        ),
    ]
