# Generated by Django 4.2 on 2026-01-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_quiz_attempt_limit_quiz_due_date_quiz_is_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='Admin_profile_pics/')),
            ],
            options={
                'verbose_name_plural': '1. Admin',
            },
        ),
    ]
