# Generated by Django 4.2 on 2026-01-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='main.course')),
            ],
            options={
                'verbose_name_plural': '15. Course Study Material',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
