# Generated by Django 4.2 on 2026-01-13 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_studymaterial_delete_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': '15. Course Study Materials'},
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='file_type',
            field=models.CharField(default='pdf', max_length=20),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.teacher'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
