# Generated by Django 4.2 on 2026-02-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_mentorshipsession_mentorshipregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(default="admin", max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="admin_profile_pics/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_super_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "16. Admins",
            },
        ),
    ]
