# Generated by Django 4.2 on 2026-02-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_courseforum_forummessage_forumnotification_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forummember',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='forummessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='forummember',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_memberships', to='main.teacher'),
        ),
        migrations.AddField(
            model_name='forummessage',
            name='sender_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_messages', to='main.teacher'),
        ),
        migrations.AddField(
            model_name='forummessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_messages', to='main.user'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='forummember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_memberships', to='main.user'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='main.user'),
        ),
        migrations.AddConstraint(
            model_name='forummember',
            constraint=models.UniqueConstraint(fields=('forum', 'user'), name='unique_forum_user'),
        ),
        migrations.AddConstraint(
            model_name='forummember',
            constraint=models.UniqueConstraint(fields=('forum', 'teacher'), name='unique_forum_teacher'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'reaction'), name='unique_message_user_reaction'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'teacher', 'reaction'), name='unique_message_teacher_reaction'),
        ),
    ]
