# Generated by Django 4.2 on 2026-02-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_user_profile_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together=set(),
        ),
    ]
